---
# Setup ruby
- include: setup.yml

- name: Install bundled gems
  bundler:
    chdir: "{{ app_dir }}"

- name: Copy dotenv
  template:
    src: .env.j2
    dest: "{{ app_dir }}/.env"

# Do migrations manually in development
- name: Migrate db
  command: bundle exec rails db:migrate
  args:
    chdir: "{{ app_dir }}"
  when: code_updated is defined and vm is not defined

- name: Precompile assets
  command: bundle exec rails assets:precompile
  args:
    chdir: "{{ app_dir }}"
  when: code_updated is defined

# Update systemd target
- include: systemd.yml
  when: code_updated is defined and vm is not defined

- name: Restart rails
  command: systemctl restart {{ app_name }}.target
  environment:
    RAILS_ENV: "{{ rails_env }}"
  when: code_updated
  become: yes
