---
- name: Export foreman to systemd
  command: foreman export systemd /lib/systemd/system -a {{ app_name }} -u {{ ansible_ssh_user }}
  args:
    chdir: "{{ app_dir }}"
  become: yes

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes
