# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 647131774d42882d200dbd66ac74150e9d33e146ed4193edc127acc72b6b6d061dd36514e5682c7092b5cf14a73d4b891df243091c119b38a17bf31486e76bfc

test:
  secret_key_base: ca54cedcc75e946366146365329879b5933a03a1908bd2220acf1db085fef529d9d9aa0cfa55ea38ce421cd801fa1583603a169c48d1c358479c54c52bc30123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
