---
- name: App server setup
  hosts: app
  gather_facts: no
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Include environment vars
      include_vars: env_vars/{{ rails_env }}.yml
  roles:
    - role: bootstrap_xenial
      tags: "bootstrap"
    - role: common
      tags: "common"
    - role: nginx
      tags: "nginx"
    - role: rails
      tags: "rails"
    - role: iso_cmd
      tags: "iso"
