---
- name: App server setup
  hosts: app
  vars_files:
    - vars.yml
  roles:
    - role: common
      tags: common
    - role: src
      tags: src
      when: vm is not defined
    - role: letsencrypt
      when: ssl
      tags: letsencrypt
    - role: nginx
      tags: nginx
    - role: rails
      tags: rails
    - role: iso_cmd
      tags: iso
