---
- name: DB server setup
  hosts: db
  gather_facts: no
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Include environment vars
      include_vars: env_vars/{{ rails_env }}.yml
      tags: always
  roles:
    - role: bootstrap_xenial
      tags:
        - bootstrap
        - always
    - role: common
      tags: common
    - role: postgres
      tags: postgres
    - role: DavidWittman.redis
      tags: redis
      become: yes
